# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml



  maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build using Maven
        run: mvn clean install

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_TOKEN=$SONAR_TOKEN \
            -v $PWD:/usr/src \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=.

      - name: OWASP Dependency Check
        run: |
          docker run --rm \
            -v $PWD:/src \
            owasp/dependency-check \
            --project "java-sec" \
            --scan /src \
            --format "HTML" \
            --out /src/dependency-check-report

      - name: Trivy Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Checkmarx (CxCLI)
        run: |
          docker run --rm \
            -v $PWD:/src \
            checkmarx/cxcli:latest \
            scan --project-name="java-app" --src="/src"

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: dependency-check-report/

